#
# Authors : 
#     Giuseppe Chiari (giuseppe.chiari@polimi.it),
#     Davide Galli (davide.galli@polimi.it),
#     Francesco Lattari (francesco.lattari@polimi.it),
#     Matteo Matteucci (matteo.matteucci@polimi.it),
#     Davide Zoni (davide.zoni@polimi.it)
#

datamodule:
  name: CoClassifierDataModule
  config:
    dataset_dir: </path/to/training/dataset>
    batch_size: 256
    num_workers: 8
    labels:
      0: 0 # noise
      1: 1 # aes
